name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      -
        name: Restore dotnet tool & dependency
        run: |
          dotnet tool restore
          dotnet restore
      -
        name: Run unit test
        run: dotnet test
